name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: [build]
    runs-on: [windows-latest]

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
    - name: Create Release ZIP archive
      run: Compress-Archive -Path Elmanager-Release/Elmanager.exe -DestinationPath Elmanager-Release.zip
    - name: Create WineRelease ZIP archive
      run: Compress-Archive -Path Elmanager-WineRelease/* -DestinationPath Elmanager-WineRelease.zip
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: 'See [changelog](https://github.com/Smibu/elmanager/blob/master/Elmanager/changelog.md).'
        draft: false
        prerelease: true
    - name: Upload Release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Elmanager-Release.zip
        asset_name: Elmanager-Release.zip
        asset_content_type: application/zip
    - name: Upload WineRelease asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Elmanager-WineRelease.zip
        asset_name: Elmanager-WineRelease.zip
        asset_content_type: application/zip
